version: "3.7"

services:
  pizza_db:
    container_name: pizza_db
    image: postgres:14.2-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql_pizza/data/
    env_file:
      - .local_env
    networks:
      - pizza_net

  pizza:
    container_name: pizza
    build: .
    restart: always
    env_file:
      - .local_env
    ports:
      - "8000:8000"
    depends_on:
      - pizza_db
    volumes:
      - migration_volume:/pizza/migrations/versions
    networks:
      - pizza_net


volumes:
  postgres_data:
    name: pizza_postgres_volume
  migration_volume:
    name: pizza_migration_volume


networks:
  pizza_net:
    driver: bridge
    name: pizza_net
