name: Django CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.10.6

    - name: Run tests
      run: |
        docker-compose -f test-docker-compose.yml up --build
        docker ps
        docker exec -it pizza pytest
