name: Pytest Coverage

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.10.6

    - name: Run containers
      run: docker-compose -f test-docker-compose.yml up -d

    - name: Run tests
      run: |
        docker-compose exec -T pizza pytest --cov-report=xml --cov=. tests/
        docker cp pizza:/pizza/coverage.xml .

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}